spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  client:
    instance:
      preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    frontend: /frontend/**
    backend: /backend/**
  sensitiveHeaders: Cookie, Set-Cookie
# ribbon:
#   ReadTimeout: 60000