spring:
  application:
    name: frontend

#это говно не работает
#  cloud:
#    config:
#      uri: http://localhost:8081

server:
  port: 12211


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#что это за параметр ниже???
    instance.preferIpAddress: true

#name: popka

