server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka-server

#
#  cloud:
#    config:
#      uri: http://localhost:8081